pipeline:
  dependencies:
    image: node:10
    pull: true
    commands:
      - node --version
      - npm --version
      - npm ci

  lint:
    image: node:10
    commands:
      - node --version
      - npm --version
      - npm run lint

  build:
    image: node:10
    commands:
      - node --version
      - npm --version
      - npm run build
